import type { CoordinatorManifest, Repository } from "../core/schema.js";

export const AGENT_FILE_MARKER = "Generated by Agent Coordinator";

function agentName(repository: Repository): string {
  return repository.agent.name ?? repository.id;
}

function description(manifest: CoordinatorManifest, repository: Repository): string {
  return (
    repository.agent.description ??
    `Owns implementation and verification limited to the ${manifest.name} '${repository.id}' repository.`
  );
}

function instructions(manifest: CoordinatorManifest, repository: Repository): string {
  const siblings = manifest.repositories
    .filter((candidate) => candidate.id !== repository.id)
    .map((candidate) => `\`${candidate.path}\``)
    .join(", ");
  const custom = repository.agent.instructions.length
    ? `\n\nRepository-specific instructions:\n${repository.agent.instructions
        .map((instruction) => `- ${instruction}`)
        .join("\n")}`
    : "";
  const verification = repository.agent.verify.length
    ? `\n\nBefore returning, run:\n${repository.agent.verify
        .map((command) => `- \`${command}\``)
        .join("\n")}`
    : "";
  const workspaceMode = manifest.workspace
    ? `\n\nBefore editing, read \`workspace.selection.${repository.id}\` in \`coordinator.yaml\` from the current coordinator revision and confirm it is active. If it is pinned, read-only, or absent, stop and report that constraint to the primary agent.`
    : manifest.workspaceManifest
      ? `\n\nBefore editing, read \`${manifest.workspaceManifest.path}\` from the current coordinator revision and confirm \`${repository.id}\` is active. If it is pinned, read-only, or absent, stop and report that constraint to the primary agent.`
      : "";
  return `Work only inside \`${repository.path}\`. Never edit the coordinator root${
    siblings ? ` or sibling repositories ${siblings}` : ""
  }.

Read the coordinator \`AGENTS.md\`, then \`${repository.path}/AGENTS.md\` when it exists, and follow applicable project skills. Preserve user changes and avoid destructive Git operations. Do not create another subagent. Return a concise summary with changed files, validation outcomes, residual risks, and cross-repository contract impacts.${workspaceMode}${custom}${verification}`;
}

function tomlString(value: string): string {
  return value.replaceAll('"""', '\\"\\"\\"');
}

export function renderCodexAgent(
  manifest: CoordinatorManifest,
  repository: Repository,
): string {
  const name = agentName(repository);
  return `# ${AGENT_FILE_MARKER}. Edit coordinator.yaml instead.
name = ${JSON.stringify(name)}
description = ${JSON.stringify(description(manifest, repository))}
nickname_candidates = [${["Atlas", "Delta", "Echo"]
    .map((nickname) => JSON.stringify(`${name} ${nickname}`))
    .join(", ")}]
developer_instructions = """
${tomlString(instructions(manifest, repository))}
"""
`;
}

export function renderCursorAgent(
  manifest: CoordinatorManifest,
  repository: Repository,
): string {
  return `---
name: ${agentName(repository)}
description: ${JSON.stringify(description(manifest, repository))}
---

<!-- ${AGENT_FILE_MARKER}. Edit coordinator.yaml instead. -->

${instructions(manifest, repository)}
`;
}

export function renderClaudeAgent(
  manifest: CoordinatorManifest,
  repository: Repository,
): string {
  return `---
name: ${agentName(repository)}
description: ${JSON.stringify(description(manifest, repository))}
model: inherit
disallowedTools: Agent
---

<!-- ${AGENT_FILE_MARKER}. Edit coordinator.yaml instead. -->

${instructions(manifest, repository)}

Read selected portable skills directly from \`.agents/skills/<skill-name>/SKILL.md\`.
`;
}

export function renderOpenCodeAgent(
  manifest: CoordinatorManifest,
  repository: Repository,
): string {
  return `---
description: ${JSON.stringify(description(manifest, repository))}
mode: subagent
permission:
  task:
    "*": deny
---

<!-- ${AGENT_FILE_MARKER}. Edit coordinator.yaml instead. -->

${instructions(manifest, repository)}
`;
}

export function renderRootAgents(manifest: CoordinatorManifest): string {
  const repositoryList = manifest.repositories
    .map((repository) => {
      const policy = `${repository.branch.mode}${repository.branch.readOnly ? ", read-only" : ""}`;
      return `- \`${repository.id}\`: \`${repository.path}\` (${policy}); delegate to the \`${agentName(repository)}\` project agent.`;
    })
    .join("\n");
  const verify = manifest.repositories
    .flatMap((repository) =>
      repository.agent.verify.map(
        (command) => `- ${repository.id}: \`${command}\``,
      ),
    )
    .join("\n");
  const workspaceManifest = manifest.workspace
    ? "\nBranch-scoped repository intent is stored in `workspace.selection` inside `coordinator.yaml`. Read it from the current coordinator HEAD before delegation. Only repositories marked active may receive implementation work; pinned or absent repositories must remain untouched even when their default policy is writable.\n"
    : manifest.workspaceManifest
      ? `\nA legacy branch-scoped workspace manifest is stored at \`${manifest.workspaceManifest.path}\`. Read the version from the current coordinator HEAD before delegation. Only repositories marked active may receive implementation work; pinned or absent repositories must remain untouched even when their default policy is writable.\n`
      : "";
  return `<!-- ${AGENT_FILE_MARKER}. Edit coordinator.yaml and run coordinator agents sync. -->

# ${manifest.name} Agent Guide

## Scope

This repository coordinates independently versioned Git subrepositories. The
root owns cross-repository decisions, integration, agent configuration, and
delivery orchestration. Repository-specific implementation belongs to the
closer child repository and its local \`AGENTS.md\`.

${repositoryList}
${workspaceManifest}

## Delegation

- Keep root integration and Git metadata in the primary agent.
- Delegate one bounded task per affected repository using the project agents
  listed above.
- Give agents exclusive path ownership and never let two agents edit the same
  repository concurrently.
- Repository agents must not create nested agents.
- Run affected agents in parallel only when their paths and contracts are
  independent.
- Every agent returns changed files, checks run, failures, and contract impact.

## Portable skills

Linked skills live at \`.agents/skills/<skill-name>/SKILL.md\`. Each registry
entry is a relative symlink to its committed source in a pinned child checkout.
Do not replace registry links. Editing through one changes its owning child
checkout immediately; commit the change in that repository, then run
\`coordinator agents sync\`.

## Git invariant

Gitlinks are the authoritative version lock. From this root, ordinary
\`git add\`, \`git commit\`, \`git pull\`, \`git push\`, \`git checkout\`, and
\`git worktree\` are coordinated by Agent Coordinator. Never repair an invariant
with reset, clean, force checkout, or discarded user changes.

## Verification

${verify || "- Run the verification commands declared by each affected child repository."}
- Run \`coordinator doctor\` before final delivery.
`;
}

export function renderCodexConfig(manifest: CoordinatorManifest): string {
  return `# ${AGENT_FILE_MARKER}. Edit coordinator.yaml instead.
model_verbosity = "low"

[agents]
max_threads = ${manifest.agents.maxParallel}
max_depth = 1
`;
}

export function renderClaudeRoot(manifest: CoordinatorManifest): string {
  return `<!-- ${AGENT_FILE_MARKER}. Edit coordinator.yaml instead. -->

# Claude Code Adapter

@../AGENTS.md

\`AGENTS.md\` is the canonical project guide. Portable skills live in
\`.agents/skills\`; interactive command adapters use
\`/${manifest.name}:<skill-name>\`.
`;
}

export function renderClaudeCommand(
  manifest: CoordinatorManifest,
  skillName: string,
): string {
  return `---
description: Load and follow the portable ${skillName} project skill.
---

<!-- ${AGENT_FILE_MARKER}. Regenerate with coordinator agents sync. -->

Follow every instruction in the project skill below. Resolve supporting-file
paths from \`.agents/skills/${skillName}/\`.

@.agents/skills/${skillName}/SKILL.md
`;
}
