import { existsSync, readFileSync } from "node:fs";
import path from "node:path";
import { CoordinatorError } from "../core/errors.js";
import type { CoordinatorManifest } from "../core/schema.js";
import { githubRepositoryName } from "../core/manifest.js";

export const CI_MARKER = "Generated by Agent Coordinator";

function outputKey(value: string): string {
  return value.replaceAll("-", "_");
}

function shellQuote(value: string): string {
  return `'${value.replaceAll("'", `'"'"'`)}'`;
}

function yamlString(value: string): string {
  return JSON.stringify(value);
}

export function deploymentConfiguration(manifest: CoordinatorManifest): object | null {
  if (!manifest.deployments) return null;
  const repositories = new Map(
    manifest.repositories.map((repository) => [repository.id, repository]),
  );
  return {
    schemaVersion: 1,
    generatedBy: "agent-coordinator",
    environments: Object.fromEntries(
      Object.entries(manifest.deployments.environments).map(([name, environment]) => [
        name,
        {
          githubEnvironment: environment.githubEnvironment,
          allowedBranches: environment.allowedBranches,
          components: Object.fromEntries(
            Object.entries(environment.components).map(([componentName, component]) => {
              const repository = repositories.get(component.repository);
              if (!repository) {
                throw new CoordinatorError(
                  `Deployment component '${componentName}' references unknown repository '${component.repository}'.`,
                );
              }
              const githubRepository = githubRepositoryName(repository.url);
              if (!githubRepository) {
                throw new CoordinatorError(
                  `Repository '${repository.id}' needs a GitHub URL for coordinated deployments.`,
                );
              }
              return [
                componentName,
                {
                  ...component,
                  branch: repository.branch,
                  path: repository.path,
                  githubRepository,
                },
              ];
            }),
          ),
        },
      ]),
    ),
  };
}

export function renderDeploymentConfiguration(manifest: CoordinatorManifest): string | null {
  const configuration = deploymentConfiguration(manifest);
  return configuration ? `${JSON.stringify(configuration, null, 2)}\n` : null;
}

function planOutputs(componentNames: string[]): string {
  return componentNames
    .flatMap((name) => {
      const key = outputKey(name);
      return [
        "required",
        "blocked",
        "reason",
        "repository",
        "workflow",
        "ref",
        "sha",
        "dispatch_inputs",
      ].map(
        (field) => `      ${key}_${field}: \${{ steps.plan.outputs.${key}_${field} }}`,
      );
    })
    .join("\n");
}

function forceInputs(componentNames: string[]): string {
  return componentNames
    .map((name) => {
      const key = outputKey(name);
      return `      force_${key}:
        description: Trigger ${name} even when its deployed revision is current
        required: false
        default: false
        type: boolean`;
    })
    .join("\n");
}

function forceEnvironment(componentNames: string[]): string {
  return componentNames
    .map((name) => {
      const key = outputKey(name);
      return `          FORCE_${key.toUpperCase()}: \${{ inputs.force_${key} }}`;
    })
    .join("\n");
}

function triggerJob(
  componentName: string,
  githubEnvironment: string,
  tokenSecret: string,
): string {
  const key = outputKey(componentName);
  return `
  trigger_${key}:
    name: ${componentName}
    needs: plan
    if: needs.plan.outputs.${key}_required == 'true'
    runs-on: ubuntu-latest
    timeout-minutes: 5
    environment: ${yamlString(githubEnvironment)}
    steps:
      - name: Trigger ${componentName} pipeline
        env:
          DESIRED_SHA: \${{ needs.plan.outputs.${key}_sha }}
          DISPATCH_INPUTS: \${{ needs.plan.outputs.${key}_dispatch_inputs }}
          GH_TOKEN: \${{ secrets.${tokenSecret} }}
          REPOSITORY: \${{ needs.plan.outputs.${key}_repository }}
          WORKFLOW: \${{ needs.plan.outputs.${key}_workflow }}
          WORKFLOW_REF: \${{ needs.plan.outputs.${key}_ref }}
        shell: bash
        run: |
          set -euo pipefail
          request=(
            --method POST
            -H 'Accept: application/vnd.github+json'
            -H 'X-GitHub-Api-Version: 2026-03-10'
            "repos/$REPOSITORY/actions/workflows/$WORKFLOW/dispatches"
            -f "ref=$WORKFLOW_REF"
          )
          while IFS=$'\\t' read -r input_key input_value; do
            request+=(-f "inputs[$input_key]=$input_value")
          done < <(jq -r 'to_entries[] | [.key, (.value | tostring)] | @tsv' <<< "$DISPATCH_INPUTS")

          response="$(gh api "\${request[@]}")"
          run_id="$(jq -r '.workflow_run_id // empty' <<< "$response")"
          run_url="$(jq -r '.html_url // empty' <<< "$response")"
          [[ -n "$run_id" && -n "$run_url" ]] || {
            echo "::error::GitHub did not return child run details"
            exit 1
          }

          child="$(gh api -H 'X-GitHub-Api-Version: 2026-03-10' "repos/$REPOSITORY/actions/runs/$run_id")"
          actual_sha="$(jq -r '.head_sha' <<< "$child")"
          if [[ "$actual_sha" != "$DESIRED_SHA" ]]; then
            gh api --method POST "repos/$REPOSITORY/actions/runs/$run_id/cancel" >/dev/null || true
            echo "::error::Triggered $actual_sha, expected $DESIRED_SHA"
            exit 1
          fi

          printf '## ${componentName} pipeline triggered\\n\\n[%s · run %s](%s)\\n' \\
            "$REPOSITORY" "$run_id" "$run_url" >> "$GITHUB_STEP_SUMMARY"
`;
}

function blockedJob(componentName: string): string {
  const key = outputKey(componentName);
  return `
  blocked_${key}:
    name: ${componentName} blocked
    needs: plan
    if: needs.plan.outputs.${key}_blocked == 'true'
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Report blocked component
        env:
          REASON: \${{ needs.plan.outputs.${key}_reason }}
        shell: bash
        run: |
          echo "::error::$REASON"
          exit 1
`;
}

export function renderEnvironmentWorkflow(
  manifest: CoordinatorManifest,
  environmentName: string,
): string {
  const deployments = manifest.deployments;
  const environment = deployments?.environments[environmentName];
  if (!deployments || !environment) {
    throw new CoordinatorError(`Unknown deployment environment '${environmentName}'.`);
  }
  const componentNames = Object.keys(environment.components);
  const triggerJobs = componentNames
    .map((name) =>
      `${triggerJob(name, environment.githubEnvironment, deployments.tokenSecret)}${blockedJob(name)}`,
    )
    .join("");
  return `# ${CI_MARKER}. Edit coordinator.yaml and run coordinator ci sync.
name: Deploy ${environmentName}

run-name: Trigger ${environmentName} from \${{ github.ref_name }}

on:
  workflow_dispatch:
    inputs:
${forceInputs(componentNames)}

permissions:
  contents: read

concurrency:
  group: ${manifest.name}-${environmentName}-coordinator
  cancel-in-progress: false

jobs:
  plan:
    name: Plan deployment triggers
    runs-on: ubuntu-latest
    timeout-minutes: 5
    environment:
      name: ${yamlString(environment.githubEnvironment)}
      deployment: false
    outputs:
${planOutputs(componentNames)}
    steps:
      - name: Checkout coordinator
        uses: actions/checkout@v6
        with:
          fetch-depth: 1
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Compare gitlinks with deployment state
        id: plan
        env:
          GH_TOKEN: \${{ secrets.${deployments.tokenSecret} }}
          PREFERRED_REF: \${{ github.ref_name }}
          PREFERRED_REF_TYPE: \${{ github.ref_type }}
${forceEnvironment(componentNames)}
        shell: bash
        run: |
          set -euo pipefail
          [[ -n "\${GH_TOKEN:-}" ]] || {
            echo "::error::${deployments.tokenSecret} is required"
            exit 1
          }
          node .coordinator/runtime/deployment-plan.mjs \\
            .coordinator/deployments.json ${shellQuote(environmentName)}
${triggerJobs}`;
}

export function loadPlannerTemplate(): string {
  const candidates = [
    path.resolve(import.meta.dirname, "../../templates/deployment-plan.mjs"),
    path.resolve(import.meta.dirname, "../templates/deployment-plan.mjs"),
  ];
  const template = candidates.find((candidate) => existsSync(candidate));
  if (!template) {
    throw new CoordinatorError("Bundled deployment planner template is missing.");
  }
  return readFileSync(template, "utf8");
}
